### ISSUE TITLE
Multi queue support for VM

### ISSUE THREAD

**Issue by Priyanka-Naik** [NetSys/bess#346] opened 2017-03-22 14:11 UTC
Hi,

Can we provide multiple queues to a VM using PMDPort created using following script?

```
my_vhost0::PMDPort(vdev='eth_vhost0,iface=/tmp/my_vhost0.sock,queues=1')
my_vhost1::PMDPort(vdev='eth_vhost1,iface=/tmp/my_vhost1.sock,queues=1')

input0::QueueInc(port=my_vhost0, qid=0) #This module will read from my_vhost0 on queue 0
input1::QueueInc(port=my_vhost1, qid=0) #This module will read from my_vhost1 on queue 0

output0::QueueOut(port=my_vhost0, qid=0) #This module will write to my_vhost0 on queue 0
output1::QueueOut(port=my_vhost1, qid=0) #This module will write to my_vhost1 on queue 0

input0 -> output1
input1 -> output0
```

**Comment by sangjinhan** [comment] 2017-03-22 15:50
Yes, you can adjust the `queues` parameter to create a Virtio PMDPort with multiple queues. After that, create QueueInc modules with different `qid` values to access individual queues.

**Comment by mitaliyad** [comment] 2017-03-22 18:19
Ok. We wanted to know this because we did the same but we got an error.

Here is the script we are using:
`my_vhost0::PMDPort(vdev='eth_vhost0,iface=/tmp/my_vhost0.sock,queues=2')
my_vhost1::PMDPort(vdev='eth_vhost1,iface=/tmp/my_vhost1.sock,queues=2')

input0::QueueInc(port=my_vhost0, qid=0) #This module will read from my_vhost0 on queue 0
input1::QueueInc(port=my_vhost1, qid=0) #This module will read from my_vhost1 on queue 0

output0::QueueOut(port=my_vhost0, qid=0) #This module will write to my_vhost0 on queue 0
output1::QueueOut(port=my_vhost1, qid=0) #This module will write to my_vhost1 on queue 0

input0 -> output1
input1 -> output0

input10::QueueInc(port=my_vhost0, qid=1) #This module will read from my_vhost0 on queue 1
input11::QueueInc(port=my_vhost1, qid=1) #This module will read from my_vhost1 on queue 1

output10::QueueOut(port=my_vhost0, qid=1) #This module will write to my_vhost0 on queue 1
output11::QueueOut(port=my_vhost1, qid=1) #This module will write to my_vhost1 on queue 1

input10 -> output11
input11 -> output10`

Error we got after running this script is: 
`*** Error: Unhandled exception in the configuration script (most recent call last)
  File "/home/mythiliserver5/bess/bessctl/conf/samples/my_inter_vm.bess", line 19, in <module>
    input10::QueueInc(port=my_vhost0, qid=1) #This module will read from my_vhost0 on queue 1
  File "/home/mythiliserver5/bess/bessctl/commands.py", line 73, in __bess_module__
    obj = mclass_obj(*args, name=module_names, **kwargs)
  File "/home/mythiliserver5/bess/bessctl/module.py", line 25, in __init__
    self.choose_arg(None, kwargs))
  File "/home/mythiliserver5/bess/bessctl/../libbess-python/bess.py", line 255, in create_module
    return self._request('CreateModule', request)
  File "/home/mythiliserver5/bess/bessctl/../libbess-python/bess.py", line 147, in _request
    raise self.Error(err, errmsg, details)
*** Error: Invalid argument
  BESS daemon response - errno=22 (EINVAL: Invalid argument)
`

Please give us some pointer with respect to this error.
Thanks

**Comment by sangjinhan** [comment] 2017-03-22 19:58
Oh, sorry. Could you try `PMDPort(vdev='..., quques=2', num_inc_q=2, num_out_q=2)` instead?

**Comment by mitaliyad** [comment] 2017-03-23 07:59
Thanks for the help. We are able to run the above script and have added the queue parameter in VM XML i.e. queues=2 in netdev parameter and the VMs are sucessfully booting. 
However when we are unable to initialize two queues corresponding to the ports in DPDK application.  We are intializing using the following method:

`rte_eth_rx_queue_setup(enabled_port, queue_id, NUMBER_OF_RX_DESCRIPTORS, rte_eth_dev_socket_id(enabled_port), NULL, rte_mempool *) 
 rte_eth_tx_queue_setup(enabled_port, queue_id, NUMBER_OF_RX_DESCRIPTORS, rte_eth_dev_socket_id(enabled_port), NULL)
`
Please guide on what we are missing. Thanks

**Comment by mitaliyad** [comment] 2017-03-23 11:22
Hi,
After going through bess.INFO, we find out that although the second queue set (Rx/Tx) is created by bess but vring corresponding to them are not enabled and hence these queue are not visible inside VM.

Here is the snapshot to bess.INFO:
`I0323 16:32:11.085374 68082 dpdk.cc:64] VHOST_CONFIG: read message VHOST_USER_SET_VRING_CALL
I0323 16:32:11.085429 68082 dpdk.cc:64] VHOST_CONFIG: vring call idx:3 file:35
I0323 16:32:20.432083 68082 dpdk.cc:64] VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
I0323 16:32:20.432231 68082 dpdk.cc:64] VHOST_CONFIG: set queue enable: 1 to qp idx: 0
I0323 16:32:20.432255 68082 dpdk.cc:64] PMD: vring0 is enabled
I0323 16:32:20.432272 68082 dpdk.cc:64] VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
I0323 16:32:20.432282 68082 dpdk.cc:64] VHOST_CONFIG: set queue enable: 1 to qp idx: 1
I0323 16:32:20.432292 68082 dpdk.cc:64] PMD: vring1 is enabled
I0323 16:32:20.432304 68082 dpdk.cc:64] VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
I0323 16:32:20.432313 68082 dpdk.cc:64] VHOST_CONFIG: set queue enable: 0 to qp idx: 2
I0323 16:32:20.432323 68082 dpdk.cc:64] PMD: **vring2 is disabled**
I0323 16:32:20.432334 68082 dpdk.cc:64] VHOST_CONFIG: read message VHOST_USER_SET_VRING_ENABLE
I0323 16:32:20.432344 68082 dpdk.cc:64] VHOST_CONFIG: set queue enable: 0 to qp idx: 3
I0323 16:32:20.432353 68082 dpdk.cc:64] PMD: **vring3 is disabled**
`

**Comment by sangjinhan** [comment] 2017-03-23 18:27
Two things to check:
* When you use the virtio devices with the kernel device driver (before binding devices to DPDK), does `ethtool -l <interface name>` shows the correct number of queues?
* Did you correctly set `nb_rx_queue` and `nb_tx_queue` the for `rte_eth_dev_configure()`?

Also, it would be worth testing `testpmd` in the VM, to make sure that the issue is not caused by DPDK.

**Comment by sangjinhan** [comment] 2017-04-06 17:34
Closing this issue until new updates...

**Closed by sangjinhan** 2017-04-06 17:34 UTC

**Comment by Priyanka-Naik** [comment] 2017-05-02 09:05
Sorry for such a late response. We have again started working on the multi-queue setup in BESS and would like your help. As you mentioned in the earlier post, the ethtool output when the BESS port is given to the VM is:

` ethtool -l ens3
Channel parameters for ens3:
Pre-set maximums:
RX:		0
TX:		0
Other:		0
Combined:	1
Current hardware settings:
RX:		0
TX:		0
Other:		0
Combined:	1` 

We re-checked the nb_rx_queue and nb_tx_queue the for rte_eth_dev_configure() and they have been configured correctly. 

We would also like to know why the second queue VRINGS appears disabled in the BESS.info file as we have shown in our previous response.
Thanks.
