### ISSUE TITLE
BESS can't re-start pipeline when running with url filter

### ISSUE THREAD

**Issue by justinemarie** [NetSys/bess#237] opened 2017-01-17 21:55 UTC
When I run a script using the url filter and I start a new script (without restarting BESS daemon), I see errors and bess crashes. Most other scripts I can just load up a new script without restarting the daemon.

```
 File "/home/justine/bess/bessctl/cli.py", line 399, in process_one_line
    self.call_func(func, args)
  File "./bessctl", line 53, in call_func
    super(BESSCLI, self).call_func(func, args)
  File "/home/justine/bess/bessctl/cli.py", line 374, in call_func
    func(*args)
  File "/home/justine/bess/bessctl/commands.py", line 706, in run_conf
    _run_file(cli, conf_file, env_map)
  File "/home/justine/bess/bessctl/commands.py", line 698, in _run_file
    _do_run_file(cli, conf_file)
  File "/home/justine/bess/bessctl/commands.py", line 653, in _do_run_file
    ret = warn(cli, 'The current pipeline will be reset.', _clear_pipeline)
  File "/home/justine/bess/bessctl/commands.py", line 496, in warn
    func(cli, *args)
  File "/home/justine/bess/bessctl/commands.py", line 610, in _clear_pipeline
    cli.bess.reset_all()
  File "/home/justine/bess/bessctl/../libbess-python/bess.py", line 129, in reset_all
    return self._request('ResetAll')
  File "/home/justine/bess/bessctl/../libbess-python/bess.py", line 92, in _request
    response = req_fn(request)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 481, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 432, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, {"created":"@1484689968.104340248","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14})>
```

**Comment by sangjinhan** [comment] 2017-01-17 22:14
Could you post `/tmp/bessd.INFO` as well?

**Comment by sangjinhan** [comment] 2017-01-21 01:36
I cannot reproduce this bug... I assume some of the patches made to UrlFilter module fixed the problem. Closing...

**Closed by sangjinhan** 2017-01-21 01:36 UTC

**Comment by barath** [comment] 2017-01-21 01:44
Yup, fixed by:

https://github.com/NetSys/bess/pull/259
